name: Update View

on:
  issues: 
    types: 
      - labeled

permissions:
  contents: read

jobs:
  build-n-run:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name : Install Dependencies
      run : |
        python3 -m venv .env
        source .env/bin/activate
        pip install git+https://github.com/OpenPecha/Automatic-View-Updater.git@push-views
    - name : Run update_view
      run : |
        echo ${{ github.event.issue.body }}
        echo $TOKEN
        python3 ./.github/scripts/update_view.py ${{ github.event.issue.body }} $TOKEN
